---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: springapp
  template:
    metadata:
      labels:
        run: springapp
    spec:
      containers:
      - name: springapp
        image: docsourav1992/spc:latest
        ports:
          - containerPort: 8080
        imagePullPolicy: IfNotPresent
