---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  labels:
    run: springapp
spec:
  type: NodePort
  selector:
    run: springapp
  ports:
    - name: http
      port: 9999
      targetPort: 8080
      protocol: TCP
